name: Check Cache For Lama Docker Image

on:
  pull_request:
    types: [synchronize, opened, reopened, edited]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/head
      
      - name: Retrieve Docker image
        uses: actions/cache@v3
        with:
          path: lama-1-30.tar
          key: lama-1-30-${{ runner.os }}-${{ hashFiles('data.bin') }}
          restore-keys: |
            lama-1-30-${{ runner.os }}-

      - name: Check if Lama-docker was restored from cache
        run: |
          if [ -f lama-1-30.tar ]; then
            echo "Lama's docker image is restored successfully."
          else
            echo "Cache not found. Exiting..."
            exit 1
          fi